name: expense_tracker
description: A comprehensive expense tracking application
version: 1.0.0

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  realm: 20.0.1
  equatable: 2.0.7
  flutter_svg: 2.0.17
  intl: 0.20.2
  fl_chart: 0.70.2
  google_fonts: 6.2.1
  shared_preferences: 2.2.2
  kiwi: 5.0.1
  focus_detector: 2.0.1 
  go_router: 15.2.4
  flutter_screenutil: 5.9.3
  flutter_native_splash: 2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.13
  mockito: 5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/onboarding/